services:
  wss:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - ORIGIN=https://undercover-drab.vercel.app
